//! Mock embedding backend for testing.
//!
//! Provides deterministic embeddings based on text hash for reproducible tests.
//!
//! ## Stability Guarantees (TD-1)
//!
//! This implementation uses SHA-256 for hashing, which provides stable,
//! reproducible embeddings across Rust versions and platforms. The same
//! text will always produce the same embedding regardless of toolchain.

use rag_core::{EmbeddingBackend, EmbeddingError};
use sha2::{Digest, Sha256};

/// A mock embedding backend that returns deterministic embeddings.
///
/// Embeddings are generated by hashing the input text with SHA-256, ensuring:
/// - Same text always produces the same embedding (stable across Rust versions)
/// - Different texts produce different embeddings
/// - Embeddings are normalized (unit length)
/// - Values are uniformly distributed in [-1, 1] before normalization (TD-3)
pub struct MockEmbeddingBackend {
    dimension: usize,
    model_id: String,
}

impl MockEmbeddingBackend {
    /// Create a new mock backend with specified dimension.
    pub fn new(dimension: usize) -> Self {
        Self {
            dimension,
            model_id: format!("mock-{}", dimension),
        }
    }

    /// Generate deterministic embedding from text using SHA-256.
    ///
    /// Uses SHA-256 for stable hashing (TD-1) and proper 32-bit extraction
    /// for uniform value distribution (TD-3).
    fn hash_to_embedding(&self, text: &str) -> Vec<f32> {
        // Use SHA-256 for stable, platform-independent hashing (TD-1)
        let initial_hash = Sha256::digest(text.as_bytes());

        let mut embedding = Vec::with_capacity(self.dimension);

        // We need `dimension` f32 values. Each SHA-256 hash gives us 32 bytes = 8 f32s.
        // For dimensions > 8, we chain hashes using counter suffix.
        let mut hash_bytes = initial_hash.to_vec();
        let mut counter: u64 = 0;

        for i in 0..self.dimension {
            // Every 8 values, generate a new hash with incremented counter
            if i > 0 && i % 8 == 0 {
                counter += 1;
                let mut hasher = Sha256::new();
                hasher.update(&initial_hash);
                hasher.update(counter.to_le_bytes());
                hash_bytes = hasher.finalize().to_vec();
            }

            // Extract 4 bytes (32 bits) for each f32 value (TD-3: full 32-bit range)
            let byte_offset = (i % 8) * 4;
            let raw_u32 = u32::from_le_bytes([
                hash_bytes[byte_offset],
                hash_bytes[byte_offset + 1],
                hash_bytes[byte_offset + 2],
                hash_bytes[byte_offset + 3],
            ]);

            // Convert to f32 in range [-1, 1] with uniform distribution
            // u32 / u32::MAX gives [0, 1], then *2 - 1 gives [-1, 1]
            let value = (raw_u32 as f64 / u32::MAX as f64) as f32 * 2.0 - 1.0;
            embedding.push(value);
        }

        // Normalize to unit length
        let norm: f32 = embedding.iter().map(|x| x * x).sum::<f32>().sqrt();
        if norm > 0.0 {
            for x in &mut embedding {
                *x /= norm;
            }
        }

        embedding
    }
}

impl EmbeddingBackend for MockEmbeddingBackend {
    fn model_id(&self) -> &str {
        &self.model_id
    }

    fn dimension(&self) -> usize {
        self.dimension
    }

    fn embed(
        &self,
        text: &str,
    ) -> impl std::future::Future<Output = Result<Vec<f32>, EmbeddingError>> + Send {
        let embedding = self.hash_to_embedding(text);
        async move { Ok(embedding) }
    }

    fn embed_batch(
        &self,
        texts: &[String],
    ) -> impl std::future::Future<Output = Result<Vec<Vec<f32>>, EmbeddingError>> + Send {
        let embeddings: Vec<Vec<f32>> = texts.iter().map(|t| self.hash_to_embedding(t)).collect();
        async move { Ok(embeddings) }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_deterministic_embeddings() {
        let backend = MockEmbeddingBackend::new(384);

        // Same text should produce same embedding
        let emb1 = backend.hash_to_embedding("hello world");
        let emb2 = backend.hash_to_embedding("hello world");
        assert_eq!(emb1, emb2);

        // Different text should produce different embedding
        let emb3 = backend.hash_to_embedding("goodbye world");
        assert_ne!(emb1, emb3);
    }

    #[test]
    fn test_correct_dimension() {
        let backend = MockEmbeddingBackend::new(768);
        let emb = backend.hash_to_embedding("test");
        assert_eq!(emb.len(), 768);
    }

    #[test]
    fn test_normalized() {
        let backend = MockEmbeddingBackend::new(384);
        let emb = backend.hash_to_embedding("test");

        let norm: f32 = emb.iter().map(|x| x * x).sum::<f32>().sqrt();
        assert!(
            (norm - 1.0).abs() < 0.001,
            "Expected unit norm, got {}",
            norm
        );
    }

    #[test]
    fn test_model_id() {
        let backend = MockEmbeddingBackend::new(384);
        assert_eq!(backend.model_id(), "mock-384");
    }
}
