//! Mock embedding backend for testing.
//!
//! Provides deterministic embeddings based on text hash for reproducible tests.

use rag_core::{EmbeddingBackend, EmbeddingError};
use sha2::{Sha256, Digest};

/// A mock embedding backend that returns deterministic embeddings.
///
/// Embeddings are generated by hashing the input text, ensuring:
/// - Same text always produces the same embedding
/// - Different texts produce different embeddings
/// - Embeddings are normalized (unit length)
pub struct MockEmbeddingBackend {
    dimension: usize,
    model_id: String,
}

impl MockEmbeddingBackend {
    /// Create a new mock backend with specified dimension.
    pub fn new(dimension: usize) -> Self {
        Self {
            dimension,
            model_id: format!("mock-{}", dimension),
        }
    }

    /// Generate deterministic embedding from text hash.
    fn hash_to_embedding(&self, text: &str) -> Vec<f32> {
        let mut hasher = Sha256::new();
        hasher.update(text.as_bytes());
        let result = hasher.finalize();

        // Use first 8 bytes as seed
        let mut bytes = [0u8; 8];
        bytes.copy_from_slice(&result[0..8]);
        let hash = u64::from_le_bytes(bytes);

        // Generate deterministic values from hash
        let mut embedding = Vec::with_capacity(self.dimension);
        let mut seed = hash;

        for _ in 0..self.dimension {
            // Simple LCG-style PRNG for deterministic values
            seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1);
            // Convert to f32 in range [-1, 1]
            let value = ((seed >> 33) as f32 / (u32::MAX as f32)) * 2.0 - 1.0;
            embedding.push(value);
        }

        // Normalize to unit length
        let norm: f32 = embedding.iter().map(|x| x * x).sum::<f32>().sqrt();
        if norm > 0.0 {
            for x in &mut embedding {
                *x /= norm;
            }
        }

        embedding
    }
}

impl EmbeddingBackend for MockEmbeddingBackend {
    fn model_id(&self) -> &str {
        &self.model_id
    }

    fn dimension(&self) -> usize {
        self.dimension
    }

    fn embed(
        &self,
        text: &str,
    ) -> impl std::future::Future<Output = Result<Vec<f32>, EmbeddingError>> + Send {
        let embedding = self.hash_to_embedding(text);
        async move { Ok(embedding) }
    }

    fn embed_batch(
        &self,
        texts: &[String],
    ) -> impl std::future::Future<Output = Result<Vec<Vec<f32>>, EmbeddingError>> + Send {
        let embeddings: Vec<Vec<f32>> = texts.iter().map(|t| self.hash_to_embedding(t)).collect();
        async move { Ok(embeddings) }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_deterministic_embeddings() {
        let backend = MockEmbeddingBackend::new(384);

        // Same text should produce same embedding
        let emb1 = backend.hash_to_embedding("hello world");
        let emb2 = backend.hash_to_embedding("hello world");
        assert_eq!(emb1, emb2);

        // Different text should produce different embedding
        let emb3 = backend.hash_to_embedding("goodbye world");
        assert_ne!(emb1, emb3);
    }

    #[test]
    fn test_correct_dimension() {
        let backend = MockEmbeddingBackend::new(768);
        let emb = backend.hash_to_embedding("test");
        assert_eq!(emb.len(), 768);
    }

    #[test]
    fn test_normalized() {
        let backend = MockEmbeddingBackend::new(384);
        let emb = backend.hash_to_embedding("test");

        let norm: f32 = emb.iter().map(|x| x * x).sum::<f32>().sqrt();
        assert!((norm - 1.0).abs() < 0.001, "Expected unit norm, got {}", norm);
    }

    #[test]
    fn test_model_id() {
        let backend = MockEmbeddingBackend::new(384);
        assert_eq!(backend.model_id(), "mock-384");
    }

    #[test]
    fn test_golden_value() {
        let backend = MockEmbeddingBackend::new(4);
        let emb = backend.hash_to_embedding("hello world");

        // Expected value derived from running with sha2 hashing:
        // [-0.4005266, -0.57599217, -0.12500009, -0.7015601]
        let expected = vec![-0.4005266, -0.57599217, -0.12500009, -0.7015601];

        assert_eq!(emb.len(), expected.len());
        for (a, b) in emb.iter().zip(expected.iter()) {
            assert!((a - b).abs() < 1e-6, "Expected {}, got {}", b, a);
        }
    }
}
